EXIT_SUCCESS = 0

ARGUMENT_ERROR = 10
INPUT_FILE_ERROR = 11
OUTPUT_FILE_ERROR = 12

XML_FORMAT_ERROR = 31
LEXICAL_ERROR = 32
SYNTAX_ERROR = 32

SEMANTIC_ERROR = 52
OPERAND_TYPE_ERROR = 53
VAR_DOES_NOT_EXIST_ERROR = 54
FRAME_DOES_NOT_EXIST_ERROR = 55
MISSING_VALUE_ERROR = 56
DIVISION_BY_ZERO_ERROR = 57
STRING_OPERATION_ERROR = 58

INTERN_ERROR = 99
